Top_50 = [
    "div:nth-child(1) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(2) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(3) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(4) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(5) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(6) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(7) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(8) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(9) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(10) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(11) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(12) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(13) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(14) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(15) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(16) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(17) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(18) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(19) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(20) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(21) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(22) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(23) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(24) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(25) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(26) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(27) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(28) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(29) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(30) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(31) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(32) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(33) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(34) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(35) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(36) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(37) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(38) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(39) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(40) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(41) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(42) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(43) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(44) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(45) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(46) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(47) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(48) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(49) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0",
    "div:nth-child(50) > .h4HgbO_Uu1JYg5UGANeQ .t_yrXoUO3qGsJS4Y6iXX > .Type__TypeElement-sc-goli3j-0"]

Top_50_Artists = [
    "div:nth-child(2) > div:nth-child(1) > div > div.gvLrgQXBFVW6m9MscfFA > div > span > a",
    "div:nth-child(2) > div:nth-child(2) > div > div.gvLrgQXBFVW6m9MscfFA > div > span > a",
    "div:nth-child(2) > div:nth-child(3) > div > div.gvLrgQXBFVW6m9MscfFA > div > span > a",
    "div:nth-child(2) > div:nth-child(4) > div > div.gvLrgQXBFVW6m9MscfFA > div > span > a",
    "div:nth-child(5) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(6) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(7) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(8) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(9) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(10) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(2) > div:nth-child(11) > div > div.gvLrgQXBFVW6m9MscfFA > div > span > a",
    "div:nth-child(12) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(13) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(14) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(15) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(16) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(17) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(18) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(19) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(20) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(21) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(22) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(23) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(24) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(25) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(26) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(27) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(28) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(29) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(30) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(31) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(32) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(33) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(34) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(35) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(36) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(37) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(38) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(39) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(40) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(41) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(42) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(43) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(44) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(45) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(46) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(47) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(48) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(49) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a",
    "div:nth-child(50) .gvLrgQXBFVW6m9MscfFA .Type__TypeElement-sc-goli3j-0 > a"]


